### ISSUE TITLE
Score of 0.67 becomes 1.00 when test and gold are swapped

### ISSUE THREAD

**Issue by goodmami** [rafaelanchieta/sema#1]
Hi, I tried testing SEMA with the following AMRs:

* A:
  ```
  (w / white
    :ARG1 (m / marble))
  ```

* B
  ```
  (m / marble
    :ARG1-of (w / white))
  ```

Here's the results:

```bash
$ python3 sema.py -t a -g b
SEMA: P 1.00 R 1.00 F1 1.00

$ python3 sema.py -t b -g a
SEMA: P 0.67 R 0.67 F1 0.67
```

I understand you do not consider the TOP triple that selects the graph root, so the 1.00 score seems ok, but why is it 0.67 in the opposite direction?

Here is Smatch, for comparison:

```bash
$ python3 smatch.py --pr -f b a
Precision: 0.75
Recall: 0.75
F-score: 0.75

$ python3 smatch.py --pr -f a b
Precision: 0.75
Recall: 0.75
F-score: 0.75
```

In this case they are the same, but in general swapping the arguments to Smatch swaps precision and recall, but the F score would be the same. Is there a reason SEMA is not symmetric, or is it a bug?

**Comment by rafaelanchieta** [comment]
Thanks, @goodmami. I just fixed this issue. However, in large corpora, neither smatch nor SEMA is completely symmetric. The values of precision and recall change if the input parameters change.

**Comment by goodmami** [comment]
Thanks!

> However, in large corpora, neither smatch nor SEMA is completely symmetric. The values of precision and recall change if the input parameters change.

What do you mean by this? With `smatch.py --pr -f LHS RHS` the precision is (matched triples / LHS triples) and recall is (matched triples / RHS triples), so swapping LHS and RHS swaps the value for precision and recall. This has been true for the corpora I've tested it against (even when LHS and RHS are larger corpora). Do you find this to not be true in practice? And is SEMA not expected to behave the same way?

**Comment by rafaelanchieta** [comment]
Yes, in practice, the value for precision and recall swap. Using the LDC2016E86 and JAMR parser.

`smatch.py -f jamr.txt gold.txt --pr --> P: 0.7 R: 0.64 F1: 0.67`
`smatch.py -f gold.txt jamr.txt --pr --> P: 0.64 R: 0.7 F1: 0.67`

And SEMA metric presents the same behavior.

**Comment by goodmami** [comment]
Great, thanks for explaining.

The recent commit fixes my test case, although it is still not always symmetric. Below I've parsed the little prince corpus with JAMR and CAMR. The Gold-vs-JAMR scores are symmetric when swapped, but not Gold-vs-CAMR:

```bash
$ python3 sema.py -g amr-bank-struct-v1.6-training.txt -t amr-bank-struct-v1.6-training.jamr.txt
SEMA: P 0.48 R 0.44 F1 0.46

$ python3 sema.py -t amr-bank-struct-v1.6-training.txt -g amr-bank-struct-v1.6-training.jamr.txt
SEMA: P 0.44 R 0.48 F1 0.46

$ python3 sema.py -t amr-bank-struct-v1.6-training.txt -g amr-bank-struct-v1.6-training.camr.txt
SEMA: P 0.42 R 0.51 F1 0.46

$ python3 sema.py -g amr-bank-struct-v1.6-training.txt -t amr-bank-struct-v1.6-training.camr.txt
SEMA: P 0.49 R 0.41 F1 0.45
```

**Comment by rafaelanchieta** [comment]
Thanks.
Later, I will see this detail.
